version: "3.9"

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9002:9002"
      - "9003:9003"
    environment:
      MINIO_ROOT_USER: tgapk
      MINIO_ROOT_PASSWORD: tg852963
    volumes:
      - /home/tgapk/minio_data:/data
    command: server /data --address ":9002" --console-address ":9003"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 60s

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /home/tgapk/redis_data:/data
    command: redis-server --appendonly yes --bind 0.0.0.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  blog-frontend:
    image: tgapk/blog-frontend:latest
    container_name: blog-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - /home/tgapk/Blog/nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tg852963
      MYSQL_DATABASE: blog   # 初始化数据库
    ports:
      - "3306:3306"
    volumes:
      - /home/tgapk/mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptg852963"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  blog-backend:
    image: tgapk/blog-backend:latest
    container_name: blog-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

