spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false
    username: root
    password: tg852963
    driver-class-name: com.mysql.cj.jdbc.Driver
#debug: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

minio:
    endpoint: http://localhost:9002
    access-key: tgapk
    secret-key: tg852963
    bucket: blog