spring:
  application:
    name: backend
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

site:
  creation-date: "2025-08-31T00:00:00"

jwt:
  secret: ReplaceWithAStrongSecretKeyForYourJWTInProduction
  expiration-ms: 86400000


